### ISSUE TITLE
c.	Incident Response Plan

### ISSUE THREAD

**Issue by 0xTestbuild** [0xTestbuild/IncidentResponseTeam8#3]

**Comment by Telcole** [comment]
[Telvina.Cole_FA23_A2.pdf](https://github.com/0xTestbuild/IncidentResponseTeam8/files/13303432/Telvina.Cole_FA23_A2.pdf)

**Comment by Telcole** [comment]
[Team 8_IR Plan.docx](https://github.com/0xTestbuild/IncidentResponseTeam8/files/13326738/Team.8_IR.Plan.docx)
