### ISSUE TITLE
f.	Threat intelligence with Heat Map

### ISSUE THREAD

**Issue by 0xTestbuild** [0xTestbuild/IncidentResponseTeam8#6]

**Comment by Telcole** [comment]
Just found this in my archives. Hope it helps.
[Threat_Intelligence_Heat_Map.pdf](https://github.com/0xTestbuild/IncidentResponseTeam8/files/13303462/Threat_Intelligence_Heat_Map.pdf)

**Comment by 0xTestbuild** [comment]
Uploaded to repository
